export const COUNTRIES = [
  { label: 'Австралия', value: 'Australia' },
  { label: 'Австрия', value: 'Austria' },
  { label: 'Азербайджан', value: 'Azerbaijan' },
  { label: 'Албания', value: 'Albania' },
  { label: 'Алжир', value: 'Algeria' },
  { label: 'Ангола', value: 'Angola' },
  { label: 'Андорра', value: 'Andorra' },
  { label: 'Аргентина', value: 'Argentina' },
  { label: 'Армения', value: 'Armenia' },
  { label: 'Афганистан', value: 'Afghanistan' },
  { label: 'Багамские Острова', value: 'The Bahamas' },
  { label: 'Бангладеш', value: 'Bangladesh' },
  { label: 'Барбадос', value: 'Barbados' },
  { label: 'Бахрейн', value: 'Bahrain' },
  { label: 'Беларусь', value: 'Belarus' },
  { label: 'Белиз', value: 'Belize' },
  { label: 'Бельгия', value: 'Belgium' },
  { label: 'Бенин', value: 'Benin' },
  { label: 'Болгария', value: 'Bulgaria' },
  { label: 'Боливия', value: 'Bolivia' },
  { label: 'Ботсвана', value: 'Botswana' },
  { label: 'Бразилия', value: 'Brazil' },
  { label: 'Бруней', value: 'Brunei' },
  { label: 'Буркина-Фасо', value: 'Burkina Faso' },
  { label: 'Бурунди', value: 'Burundi' },
  { label: 'Бутан', value: 'Bhutan' },
  { label: 'Вануату', value: 'Vanuatu' },
  { label: 'Ватикан', value: 'Vatican City' },
  { label: 'Великобритания', value: 'United Kingdom' },
  { label: 'Венгрия', value: 'Hungary' },
  { label: 'Венесуэла', value: 'Venezuela' },
  { label: 'Вьетнам', value: 'Vietnam' },
  { label: 'Габон', value: 'Gabon' },
  { label: 'Гаити', value: 'Haiti' },
  { label: 'Гамбия', value: 'The Gambia' },
  { label: 'Гана', value: 'Ghana' },
  { label: 'Гватемала', value: 'Guatemala' },
  { label: 'Гвинея', value: 'Guinea' },
  { label: 'Гвинея-Бисау', value: 'Guinea-Bissau' },
  { label: 'Германия', value: 'Germany' },
  { label: 'Гондурас', value: 'Honduras' },
  { label: 'Греция', value: 'Greece' },
  { label: 'Гренада', value: 'Grenada' },
  { label: 'Грузия', value: 'Georgia' },
  { label: 'Дания', value: 'Denmark' },
  { label: 'Джибути', value: 'Djibouti' },
  { label: 'Доминика', value: 'Dominica' },
  { label: 'Доминиканская Республика', value: 'Dominican Republic' },
  { label: 'Египет', value: 'Egypt' },
  { label: 'Замбия', value: 'Zambia' },
  { label: 'Зимбабве', value: 'Zimbabwe' },
  { label: 'Израиль', value: 'Israel' },
  { label: 'Индия', value: 'India' },
  { label: 'Индонезия', value: 'Indonesia' },
  { label: 'Иордания', value: 'Jordan' },
  { label: 'Ирак', value: 'Iraq' },
  { label: 'Иран', value: 'Iran' },
  { label: 'Ирландия', value: 'Ireland' },
  { label: 'Исландия', value: 'Iceland' },
  { label: 'Испания', value: 'Spain' },
  { label: 'Италия', value: 'Italy' },
  { label: 'Йемен', value: 'Yemen' },
  { label: 'Кабо-Верде', value: 'Cape Verde' },
  { label: 'Казахстан', value: 'Kazakhstan' },
  { label: 'Камбоджа', value: 'Cambodia' },
  { label: 'Камерун', value: 'Cameroon' },
  { label: 'Канада', value: 'Canada' },
  { label: 'Катар', value: 'Qatar' }, // если будет добавлен
  { label: 'Кения', value: 'Kenya' },
  { label: 'Кипр', value: 'Cyprus' },
  { label: 'Киргизия', value: 'Kyrgyzstan' },
  { label: 'Кирибати', value: 'Kiribati' },
  { label: 'КНДР', value: 'North Korea' },
  { label: 'Колумбия', value: 'Colombia' },
  { label: 'Коморы', value: 'Comoros' },
  { label: 'Корея (Южная)', value: 'South Korea' },
  { label: 'Коста-Рика', value: 'Costa Rica' },
  { label: 'Кот-д’Ивуар', value: 'Ivory Coast' },
  { label: 'Куба', value: 'Cuba' },
  { label: 'Кувейт', value: 'Kuwait' },
  { label: 'Лаос', value: 'Laos' },
  { label: 'Латвия', value: 'Latvia' },
  { label: 'Лесото', value: 'Lesotho' },
  { label: 'Ливан', value: 'Lebanon' },
  { label: 'Либерия', value: 'Liberia' },
  { label: 'Ливия', value: 'Libya' },
  { label: 'Литва', value: 'Lithuania' },
  { label: 'Лихтенштейн', value: 'Liechtenstein' },
  { label: 'Люксембург', value: 'Luxembourg' },
  { label: 'Маврикий', value: 'Mauritius' },
  { label: 'Мавритания', value: 'Mauritania' },
  { label: 'Мадагаскар', value: 'Madagascar' },
  { label: 'Македония', value: 'Macedonia' },
  { label: 'Малави', value: 'Malawi' },
  { label: 'Малайзия', value: 'Malaysia' },
  { label: 'Мали', value: 'Mali' },
  { label: 'Мальдивы', value: 'Maldives' },
  { label: 'Мальта', value: 'Malta' },
  { label: 'Марокко', value: 'Morocco' },
  { label: 'Маршалловы Острова', value: 'Marshall Islands' },
  { label: 'Мексика', value: 'Mexico' },
  { label: 'Микронезия', value: 'Micronesia' },
  { label: 'Мозамбик', value: 'Mozambique' },
  { label: 'Молдова', value: 'Moldova' },
  { label: 'Монако', value: 'Monaco' },
  { label: 'Монголия', value: 'Mongolia' },
  { label: 'Мьянма', value: 'Myanmar' },
  { label: 'Намибия', value: 'Namibia' },
  { label: 'Науру', value: 'Nauru' },
  { label: 'Непал', value: 'Nepal' },
  { label: 'Нигер', value: 'Niger' },
  { label: 'Нигерия', value: 'Nigeria' },
  { label: 'Нидерланды', value: 'Netherlands' },
  { label: 'Никарагуа', value: 'Nicaragua' },
  { label: 'Новая Зеландия', value: 'New Zealand' },
  { label: 'Норвегия', value: 'Norway' },
  { label: 'ОАЭ', value: 'United Arab Emirates' },
  { label: 'Оман', value: 'Oman' }, // если будет добавлен
  { label: 'Пакистан', value: 'Pakistan' },
  { label: 'Палау', value: 'Palau' },
  { label: 'Панама', value: 'Panama' },
  { label: 'Папуа — Новая Гвинея', value: 'Papua New Guinea' },
  { label: 'Парагвай', value: 'Paraguay' },
  { label: 'Перу', value: 'Peru' },
  { label: 'Польша', value: 'Poland' },
  { label: 'Португалия', value: 'Portugal' },
  { label: 'Россия', value: 'Russia' },
  { label: 'Руанда', value: 'Rwanda' },
  { label: 'Румыния', value: 'Romania' },
  { label: 'Сальвадор', value: 'El Salvador' },
  { label: 'Самоа', value: 'Samoa' },
  { label: 'Сан-Марино', value: 'San Marino' },
  { label: 'Сан-Томе и Принсипи', value: 'Sao Tome and Principe' },
  { label: 'Саудовская Аравия', value: 'Saudi Arabia' },
  { label: 'Сенегал', value: 'Senegal' },
  {
    label: 'Сент-Винсент и Гренадины',
    value: 'Saint Vincent and the Grenadines',
  },
  { label: 'Сент-Китс и Невис', value: 'Saint Kitts and Nevis' },
  { label: 'Сент-Люсия', value: 'Saint Lucia' },
  { label: 'Сербия', value: 'Serbia' },
  { label: 'Сейшелы', value: 'Seychelles' },
  { label: 'Сингапур', value: 'Singapore' },
  { label: 'Сирия', value: 'Syria' },
  { label: 'Словакия', value: 'Slovakia' },
  { label: 'Словения', value: 'Slovenia' }, // если будет добавлен
  { label: 'Соломоновы Острова', value: 'Solomon Islands' },
  { label: 'Сомали', value: 'Somalia' },
  { label: 'Судан', value: 'Sudan' },
  { label: 'Суринам', value: 'Suriname' },
  { label: 'США', value: 'United States' },
  { label: 'Таджикистан', value: 'Tajikistan' },
  { label: 'Таиланд', value: 'Thailand' },
  { label: 'Танзания', value: 'Tanzania' },
  { label: 'Того', value: 'Togo' },
  { label: 'Тонга', value: 'Tonga' },
  { label: 'Тринидад и Тобаго', value: 'Trinidad and Tobago' },
  { label: 'Тувалу', value: 'Tuvalu' },
  { label: 'Тунис', value: 'Tunisia' },
  { label: 'Туркмения', value: 'Turkmenistan' },
  { label: 'Турция', value: 'Turkey' },
  { label: 'Уганда', value: 'Uganda' },
  { label: 'Узбекистан', value: 'Uzbekistan' },
  { label: 'Украина', value: 'Ukraine' },
  { label: 'Уругвай', value: 'Uruguay' },
  { label: 'Фиджи', value: 'Fiji' },
  { label: 'Филиппины', value: 'Philippines' },
  { label: 'Финляндия', value: 'Finland' },
  { label: 'Франция', value: 'France' },
  { label: 'Хорватия', value: 'Croatia' },
  { label: 'Чад', value: 'Chad' },
  { label: 'Черногория', value: 'Montenegro' },
  { label: 'Чехия', value: 'Czech Republic' },
  { label: 'Чили', value: 'Chile' },
  { label: 'Китай', value: 'China' },
  { label: 'Швейцария', value: 'Switzerland' },
  { label: 'Швеция', value: 'Sweden' },
  { label: 'Шри-Ланка', value: 'Sri Lanka' },
  { label: 'Эсватини', value: 'Swaziland' },
  { label: 'Эквадор', value: 'Ecuador' },
  { label: 'Экваториальная Гвинея', value: 'Equatorial Guinea' },
  { label: 'Эритрея', value: 'Eritrea' },
  { label: 'Эстония', value: 'Estonia' },
  { label: 'Эфиопия', value: 'Ethiopia' },
  { label: 'ЮАР', value: 'South Africa' },
  { label: 'Ямайка', value: 'Jamaica' },
  { label: 'Япония', value: 'Japan' },
];
