import { IProduct } from '../interfaces';
import { CATEGORIES } from './categories/categories.const';

export const PRODUCTS: IProduct[] = [
  {
    id: 1,
    name: 'Яблоки Гала',
    description:
      'Свежие яблоки сорта Гала, хрустящие и сочные.Плоды Ред принца имеют вес около 200 г.хранить при температуре воздуха от 0С до +4С и относительной влажности воздуха 80-90 %. Срок годности: 60 суток с даты упаковывания, указанной на стикере. Яблоки округло-конической формы, багрового оттенка. Мякоть сочная и мягкая, наделённая тонким ароматом, сладкая на вкус, с лёгкой кислинкой послевкусия.',
    images: [
      'https://swlife.ru/image/cache/catalog/product/f0/a1/f0a1349d79e262597b5e00a386b8a796-628x628.webp',
      'https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg',
    ],
    price: 120,
    category: { name: CATEGORIES[0].name, value: CATEGORIES[0].value },
    subcategory: {
      name: CATEGORIES[0].categories[0].subcategories[0].name, // Фрукты
      value: CATEGORIES[0].categories[0].subcategories[0].value,
    },
    filters: [],
    exporter: {
      id: 1,
      name: 'ООО "Фруктовая долина"',
    },
    measure: 'gr',
    specialConditions: 'Скидка 5% при покупке от 3 кг',
    inStock: true,
    volume: 1000,
    country: 'Россия',
    region: 'Краснодарский край',
    giftBox: false,
    certificates: [
      'https://www.serconsrus.ru/app/uploads/2024/08/attest-organa-os.jpg',
      'https://nvppoint.com/wp-content/uploads/2017/12/Sertifikat-dobrovolnyiy-import-1-724x1024.jpg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYUV7_nstWaCEP_Xbr9XLxNdQRgQMZ2fv-_81pZz3OqOFDtfqYeuAMsPUzbOk8NknaNfs&usqp=CAU',
    ],
    manufacturer: 'Яблочный рай',
    isManufacturer: false,
    brand: 'Gala',
    abv: 0,
  },
  {
    id: 2,
    name: 'Говядина на кости',
    description:
      '«Говяжья вырезка — длинная мышца, которая расположена на спине животного и проходит вдоль позвоночника. Это самая лучшая часть говяжьей туши, отличается исключительной мягкостью, а тонкие жировые прослойки делают блюда из вырезки по-настоящему сочными. Именно из вырезки готовят вкуснейшие мясные деликатесы: вкусные жареные медальоны, стейки, ростбиф, бефстроганов, филе-миньон, карпаччо и многое другое. Также из говяжьей вырезки можно приготовить вяленую бастурму, запечь ее в духовке со специями, пожарить на гриле.»',
    images: [
      'https://ecomarket.ru/imgs/products/9582/govyadina--vyrezka-ohl--zachischennaya---1-8-kg--orenbiv-zerno_1726597122.jpg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSuhcSVLnL4WCXNzfzIy9SmGvYO-QhOakkXw&s',
    ],
    price: 450,
    category: { name: CATEGORIES[0].name, value: CATEGORIES[0].value },
    subcategory: {
      name: CATEGORIES[0].categories[1].subcategories[0].name, // Мясо
      value: CATEGORIES[0].categories[1].subcategories[0].value,
    },
    filters: [{ name: 'Тип', selectedValues: ['Говядина'] }],
    exporter: {
      id: 2,
      name: 'АО "Мясной дом"',
    },
    measure: 'gr',
    specialConditions: '',
    inStock: true,
    volume: 1000,
    country: 'Казахстан',
    region: 'Алматинская область',
    isManufacturer: false,
    giftBox: true,
    certificates: [
      'https://www.serconsrus.ru/app/uploads/2024/08/attest-organa-os.jpg',
      'https://nvppoint.com/wp-content/uploads/2017/12/Sertifikat-dobrovolnyiy-import-1-724x1024.jpg',
      'https://msk.gsg-rt.ru/images/seo/%D0%90%D1%82%D1%82%D0%B5%D1%81%D1%82%D0%B0%D1%82%20%D0%B0%D0%BA%D0%BA%D1%80%D0%B5%D0%B4%D0%B8%D1%82%D0%B0%D1%86%D0%B8%D0%B8%201-4.jpg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYUV7_nstWaCEP_Xbr9XLxNdQRgQMZ2fv-_81pZz3OqOFDtfqYeuAMsPUzbOk8NknaNfs&usqp=CAU',
    ],
    manufacturer: 'АО "Мясной дом"',
    brand: 'Фермерская продукция',
    abv: 0,
  },
  {
    id: 3,
    name: 'Сыр Российский',
    description: 'Классический твердый сыр, выдержанный вкус.',
    images: [],
    price: 380,
    category: { name: CATEGORIES[0].name, value: CATEGORIES[0].value },
    subcategory: {
      name: CATEGORIES[0].categories[2].subcategories[1].name, // Сыр
      value: CATEGORIES[0].categories[2].subcategories[1].value,
    },
    filters: [{ name: 'Тип', selectedValues: ['Твердый'] }],
    exporter: { id: 3, name: 'ООО "Молочный комбинат"' },
    measure: 'gr',
    specialConditions: 'Сыр в нарезке — скидка 10%',
    inStock: true,
    volume: 500,
    country: 'Россия',
    region: 'Вологодская область',
    isManufacturer: true,
    giftBox: false,
    certificates: [
      'https://www.serconsrus.ru/app/uploads/2024/08/attest-organa-os.jpg',
    ],
    manufacturer: 'ООО "Молочный комбинат"',
    brand: 'Сыроварня №1',
    abv: 0,
  },
  {
    id: 4,
    name: 'Пшеничный хлеб',
    description: 'Свежий хлеб из пшеничной муки, выпечка дня.',
    images: [],
    price: 55,
    category: { name: CATEGORIES[0].name, value: CATEGORIES[0].value },
    subcategory: {
      name: CATEGORIES[0].categories[4].subcategories[0].name, // Хлеб
      value: CATEGORIES[0].categories[4].subcategories[0].value,
    },
    filters: [{ name: 'Тип', selectedValues: ['Белый'] }],
    exporter: { id: 4, name: 'ИП "Пекарь Иванов"' },
    measure: 'gr',
    specialConditions: '',
    inStock: true,
    volume: 400,
    country: 'Россия',
    region: 'Московская область',
    isManufacturer: false,
    giftBox: false,
    certificates: [],
    manufacturer: 'ИП "Пекарь Иванов"',
    brand: 'Хлебный край',
    abv: 0,
  },
  {
    id: 5,
    name: 'Оливковое масло Extra Virgin',
    description: 'Натуральное масло холодного отжима, без добавок.',
    images: [],
    price: 750,
    category: { name: CATEGORIES[0].name, value: CATEGORIES[0].value },
    subcategory: {
      name: CATEGORIES[0].categories[5].subcategories[3].name, // Масла
      value: CATEGORIES[0].categories[5].subcategories[3].value,
    },
    filters: [{ name: 'Тип', selectedValues: ['Оливковое'] }],
    exporter: { id: 5, name: 'ООО "Масляный мир"' },
    measure: 'ml',
    specialConditions: 'Скидка при покупке от 3 л',
    inStock: true,
    volume: 1000,
    country: 'Греция',
    region: 'Крит',
    isManufacturer: false,
    giftBox: true,
    certificates: [
      'https://www.serconsrus.ru/app/uploads/2024/08/attest-organa-os.jpg',
      'https://nvppoint.com/wp-content/uploads/2017/12/Sertifikat-dobrovolnyiy-import-1-724x1024.jpg',
      'https://msk.gsg-rt.ru/images/seo/%D0%90%D1%82%D1%82%D0%B5%D1%81%D1%82%D0%B0%D1%82%20%D0%B0%D0%BA%D0%BA%D1%80%D0%B5%D0%B4%D0%B8%D1%82%D0%B0%D1%86%D0%B8%D0%B8%201-4.jpg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYUV7_nstWaCEP_Xbr9XLxNdQRgQMZ2fv-_81pZz3OqOFDtfqYeuAMsPUzbOk8NknaNfs&usqp=CAU',
    ],
    manufacturer: 'Яблочный рай',
    brand: 'Greek Gold',
    abv: 0,
  },
];
